export type ExperienceLang = 'de' | 'en';

export const chapters = [
  { id: 'journey-start', short: 'Vision', label: { de: 'Vision', en: 'Vision' } },
  { id: 'fragmentierung', short: 'Heute', label: { de: 'Ausgangslage', en: 'Today' } },
  { id: 'journey-solutions', short: 'System', label: { de: 'Das System', en: 'The system' } },
  { id: 'verkaufssystem', short: 'Web', label: { de: 'Website', en: 'Website' } },
  { id: 'marketing-engine', short: 'Reach', label: { de: 'Marketing', en: 'Marketing' } },
  { id: 'business-os', short: 'Flow', label: { de: 'Prozesse', en: 'Processes' } },
  { id: 'daten-intelligenz', short: 'Data', label: { de: 'Daten & AI', en: 'Data & AI' } },
  { id: 'journey-references', short: 'Proof', label: { de: 'Projekte', en: 'Projects' } },
  { id: 'journey-about', short: 'Marcel', label: { de: 'Zusammenarbeit', en: 'Collaboration' } },
  { id: 'journey-contact', short: 'Start', label: { de: 'Projektstart', en: 'Project start' } },
] as const;

export const systemNodes = {
  de: ['Website', 'Marketing', 'Kunden', 'E-Mail', 'Offerten', 'Projekte', 'Finanzen', 'Mitarbeitende', 'Analytics', 'Daten', 'Termine', 'Social Media'],
  en: ['Website', 'Marketing', 'Customers', 'Email', 'Quotes', 'Projects', 'Finance', 'Team', 'Analytics', 'Data', 'Calendar', 'Social media'],
};

export const azItems = {
  de: [
    ['A', 'Automationen', 'Wiederkehrende Schritte laufen verlässlich im Hintergrund.'],
    ['B', 'Business Intelligence', 'Relevante Zahlen werden zu einer klaren Entscheidungsgrundlage.'],
    ['C', 'CRM', 'Kunden, Anfragen, Kommunikation und Dokumente an einem Ort.'],
    ['D', 'Datenbanken', 'Information einmal erfassen und überall korrekt nutzen.'],
    ['E', 'ERP', 'Aufträge, Projekte, Ressourcen und Finanzen gemeinsam steuern.'],
    ['F', 'Finanzprozesse', 'Von der Offerte bis zur Zahlung bleibt der Vorgang verbunden.'],
    ['G', 'GEO', 'Inhalte werden für klassische Suche und AI-Antwortsysteme verständlich.'],
    ['H', 'Hosting', 'Ein stabiler, wartbarer Betrieb gehört zur Lösung.'],
    ['I', 'Integrationen', 'Bestehende Werkzeuge tauschen Daten sicher über Schnittstellen aus.'],
    ['J', 'Journey Automation', 'Jeder Kontakt erhält zur richtigen Zeit den nächsten sinnvollen Schritt.'],
    ['K', 'Kundenverwaltung', 'Ein aktueller Datensatz begleitet die gesamte Kundenbeziehung.'],
    ['L', 'Lead Management', 'Anfragen werden erfasst, qualifiziert und nachvollziehbar bearbeitet.'],
    ['M', 'Marketing', 'Kanäle, Inhalte und Conversion arbeiten auf ein gemeinsames Ziel hin.'],
    ['N', 'Newsletter', 'Relevante Kontakte werden kontrolliert und persönlich weitergeführt.'],
    ['O', 'Offerten', 'Angebote entstehen aus vorhandenen Daten und werden digital freigegeben.'],
    ['P', 'Projektmanagement', 'Aufgaben, Termine, Ressourcen und Fortschritt bleiben sichtbar.'],
    ['Q', 'Qualitätssicherung', 'Tests und klare Freigaben schützen die wichtigsten Abläufe.'],
    ['R', 'Reporting', 'Das System zeigt, was passiert und wo Handlungsbedarf besteht.'],
    ['S', 'Security, SaaS & SEO', 'Sicherheit, Auffindbarkeit und Softwarearchitektur werden gemeinsam gedacht.'],
    ['T', 'Tracking', 'Messung zeigt, welche Wege zu relevanten Anfragen führen.'],
    ['U', 'UX & UI', 'Komplexe Abläufe werden verständlich und angenehm bedienbar.'],
    ['V', 'Verkauf', 'Vom Erstkontakt bis zum Auftrag bleibt jeder Schritt nachvollziehbar.'],
    ['W', 'Webdesign', 'Die sichtbare Oberfläche übersetzt Strategie und System in Vertrauen.'],
    ['X', 'Individuelle Integrationen', 'Sonderfälle werden sauber in die Architektur eingebunden.'],
    ['Y', 'Your Business', 'Die Lösung folgt deinem Unternehmen, nicht einer Standardvorlage.'],
    ['Z', 'Zeiterfassung', 'Aufwand fliesst direkt in Projekte, Auswertung und Abrechnung.'],
  ],
  en: [
    ['A', 'Automation', 'Recurring steps run reliably in the background.'],
    ['B', 'Business intelligence', 'Relevant figures become a clear basis for decisions.'],
    ['C', 'CRM', 'Customers, enquiries, communication and documents in one place.'],
    ['D', 'Databases', 'Enter information once and use it correctly everywhere.'],
    ['E', 'ERP', 'Manage orders, projects, resources and finance together.'],
    ['F', 'Financial processes', 'The process stays connected from quote to payment.'],
    ['G', 'GEO', 'Content is clear to classic search and AI answer systems.'],
    ['H', 'Hosting', 'Stable, maintainable operation is part of the solution.'],
    ['I', 'Integrations', 'Existing tools exchange data securely through interfaces.'],
    ['J', 'Journey automation', 'Every contact receives the next useful step at the right time.'],
    ['K', 'Customer management', 'One current record supports the entire customer relationship.'],
    ['L', 'Lead management', 'Enquiries are captured, qualified and processed transparently.'],
    ['M', 'Marketing', 'Channels, content and conversion work towards one shared goal.'],
    ['N', 'Newsletters', 'Relevant contacts are nurtured carefully and personally.'],
    ['O', 'Offers', 'Quotes use existing data and can be approved digitally.'],
    ['P', 'Project management', 'Tasks, schedules, resources and progress stay visible.'],
    ['Q', 'Quality assurance', 'Tests and clear approvals protect critical workflows.'],
    ['R', 'Reporting', 'The system shows what is happening and where action is needed.'],
    ['S', 'Security, SaaS & SEO', 'Security, discoverability and architecture are designed together.'],
    ['T', 'Tracking', 'Measurement reveals which journeys create relevant enquiries.'],
    ['U', 'UX & UI', 'Complex processes become clear and pleasant to use.'],
    ['V', 'Sales', 'Every step from first contact to order remains traceable.'],
    ['W', 'Web design', 'The visible interface translates strategy and systems into trust.'],
    ['X', 'Custom integrations', 'Special cases are integrated cleanly into the architecture.'],
    ['Y', 'Your business', 'The solution follows your company, not a standard template.'],
    ['Z', 'Time tracking', 'Effort flows directly into projects, reporting and invoicing.'],
  ],
} as const;

export const flowSteps = {
  de: ['Google-Suche', 'Website', 'Anfrage', 'CRM', 'Termin', 'Beratung', 'Offerte', 'Freigabe', 'Auftrag', 'Projekt'],
  en: ['Google search', 'Website', 'Enquiry', 'CRM', 'Meeting', 'Consultation', 'Quote', 'Approval', 'Order', 'Project'],
};

export const copy = {
  de: {
    skip: 'Zum Inhalt springen', menu: 'Kapitel', close: 'Schliessen', project: 'Projekt besprechen', discover: 'System entdecken',
    heroEyebrow: 'DIGITALE UNTERNEHMENSSYSTEME · BERN, SCHWEIZ',
    heroTitleA: 'Dein digitales Unternehmen.', heroTitleB: 'Aus einem Guss.',
    heroText: 'Ich verbinde Website, Marketing, Daten, CRM, ERP, AI und Automationen zu einem System, das Kunden gewinnt und Arbeit reduziert.',
    heroNote: 'Individuell entwickelt. Persönlich verantwortet.',
    problemEyebrow: 'DIE AUSGANGSLAGE', problemTitle: 'Das Problem sind nicht zu wenige Tools.', problemTitleGold: 'Sondern zu viele Übergaben.',
    problemText: 'Daten werden kopiert. Anfragen gehen verloren. Mitarbeitende suchen Informationen. Jede Insellösung erzeugt neue Arbeit zwischen den Systemen.',
    problemQuote: 'Software hilft erst dann, wenn sie zusammenspielt.',
    systemEyebrow: 'DIE TRANSFORMATION', systemTitle: 'Aus Einzellösungen wird ein System.',
    systemText: 'Ich analysiere zuerst Abläufe, Ziele und bestehende Werkzeuge. Danach entsteht eine Architektur, in der jeder Baustein eine klare Aufgabe erfüllt.',
    systemCore: 'DEIN SYSTEM', systemPrinciple: 'Nicht mehr Software. Die richtige Software.', systemCta: 'Was wäre für mein Unternehmen sinnvoll?',
    webEyebrow: 'WEBSITE ALS VERKAUFSSYSTEM', webTitle: 'Deine Website hört nicht beim Design auf.', webTitleGold: 'Sie beginnt dort erst zu arbeiten.',
    webText: 'Jeder Kontakt kann strukturiert weitergeführt werden – von der ersten Suche bis zum Auftrag und darüber hinaus.',
    flowLabel: 'LIVE BUSINESS FLOW', flowHint: 'Der Datenimpuls folgt dem gesamten Prozess.',
    marketingEyebrow: 'MARKETING ENGINE', marketingTitle: 'Marketing endet nicht beim Klick.',
    marketingText: 'Suche, Social Media, Content, Kampagnen und Empfehlungen führen in ein gemeinsames Lead-System. Dort werden Kontakte sinnvoll qualifiziert, weitergeführt und ausgewertet.',
    geoTitle: 'Gefunden werden, wo Entscheidungen beginnen.', geoText: 'Technische SEO, klare Informationsarchitektur, strukturierte Daten und semantische Inhalte machen dein Angebot für Menschen, Suchmaschinen und AI-Antwortsysteme verständlich – ohne Ranking-Versprechen.',
    osEyebrow: 'DEIN BUSINESS OS', osTitle: 'Die Website ist nur die Vorderseite.',
    osText: 'Dahinter können genau die Module entstehen, die dein Team wirklich braucht. Kein Funktionsfriedhof. Keine Standardsoftware, die den Prozess diktiert.',
    dashboardEyebrow: 'MANAGEMENT COCKPIT · DEMODATEN', dashboardTitle: 'Wissen, was im Unternehmen passiert.', dashboardText: 'Nicht zehn Tools öffnen. Eine klare Sicht auf die Informationen, die jetzt relevant sind.',
    azEyebrow: 'VON A BIS Z', azTitle: 'Ein Ansprechpartner. Viele Möglichkeiten.', azText: 'Die Breite ist kein Paket, das du kaufen musst. Sie ist die Fähigkeit, die richtigen Teile sauber miteinander zu verbinden.',
    dataEyebrow: 'DATEN · SECURITY · AI', dataTitle: 'Eine verlässliche Architektur unter der Oberfläche.',
    dataText: 'Daten werden einmal erfasst, kontrolliert weitergegeben und nur für die jeweilige Rolle zugänglich gemacht. AI unterstützt konkrete Schritte – nachvollziehbar und mit menschlicher Kontrolle.',
    securityTitle: 'Sicherheit ist kein Zusatz.', securityText: 'Privacy by Design, Rollen, Authentifizierung, Datenminimierung, sichere Schnittstellen, Backups und Logging werden von Beginn an berücksichtigt. Schweizer Datenschutzanforderungen und die DSGVO werden je nach Projektkontext geprüft; pauschale Compliance-Garantien gibt es nicht.',
    aiTitle: 'AI, die Arbeit abnimmt.', aiText: 'Eine Anfrage klassifizieren, einen CRM-Datensatz anlegen, die Zuständigkeit bestimmen, einen Antwortentwurf vorbereiten und ein Follow-up planen – kontrolliert statt automatisch um jeden Preis.',
    casesEyebrow: 'BEWEIS STATT BEHAUPTUNG', casesTitle: 'Systeme, die bereits Substanz haben.', casesText: 'Echte Projekte aus Strategie, Marke, UX, Frontend, Backend, Daten und Prozessen. Status und Grenzen sind transparent ausgewiesen.', caseCta: 'Case ansehen', live: 'Live öffnen',
    aboutEyebrow: 'MARCEL SPAHR · DIGITALSTUDIO BERN', aboutTitle: 'Du musst nicht zwischen Business, Design und Technik übersetzen.',
    aboutText: 'Ich begleite dein Projekt persönlich – von der Analyse über UX und Architektur bis zur Einführung. Wirtschaftsinformatik, Werbetechnik und langjährige Praxis in IT, Projekten, Marketing und Verkauf treffen in einer Verantwortung zusammen.',
    aboutQuote: 'Ich höre zuerst zu, frage nach und baue danach nur, was im Alltag wirklich hilft.',
    facts: [['15+', 'Jahre Praxis in Technologie und Kundenprojekten'], ['HF', 'Wirtschaftsinformatik in der Abschlussphase'], ['01', 'Verantwortliche Person von Analyse bis Go-live'], ['Bern', 'Standort, Projekte in der Schweiz und darüber hinaus']],
    finalA: 'Dein Unternehmen braucht nicht mehr Tools.', finalB: 'Es braucht ein System.', finalText: 'Lass uns herausfinden, welche Architektur zu deinem Unternehmen, deinen Menschen und deinen Zielen passt.',
    legal: 'Datenschutz und Impressum', privacy: 'Datenschutz', imprint: 'Impressum', footerLine: 'Digitale Unternehmenssysteme. Persönlich entwickelt in Bern.',
  },
  en: {
    skip: 'Skip to content', menu: 'Chapters', close: 'Close', project: 'Discuss your project', discover: 'Discover the system',
    heroEyebrow: 'DIGITAL BUSINESS SYSTEMS · BERN, SWITZERLAND',
    heroTitleA: 'Your digital business.', heroTitleB: 'Built as one system.',
    heroText: 'I connect websites, marketing, data, CRM, ERP, AI and automation into one system that wins customers and reduces work.',
    heroNote: 'Custom-built. Personally accountable.',
    problemEyebrow: 'THE CURRENT REALITY', problemTitle: 'The problem is not a lack of tools.', problemTitleGold: 'It is the gaps between them.',
    problemText: 'Data is copied. Enquiries get lost. Teams search for information. Every isolated solution creates more work between systems.',
    problemQuote: 'Software only helps when it works together.',
    systemEyebrow: 'THE TRANSFORMATION', systemTitle: 'Separate solutions become one system.',
    systemText: 'I first analyse workflows, goals and existing tools. Then I create an architecture in which every component has a clear purpose.',
    systemCore: 'YOUR SYSTEM', systemPrinciple: 'Not more software. The right software.', systemCta: 'What would make sense for my company?',
    webEyebrow: 'WEBSITE AS A SALES SYSTEM', webTitle: 'Your website does not stop at design.', webTitleGold: 'That is where it starts working.',
    webText: 'Every contact can move forward in a structured way – from the first search to the order and beyond.',
    flowLabel: 'LIVE BUSINESS FLOW', flowHint: 'The data signal follows the complete process.',
    marketingEyebrow: 'MARKETING ENGINE', marketingTitle: 'Marketing does not end at the click.',
    marketingText: 'Search, social media, content, campaigns and referrals feed one lead system. Contacts are qualified, nurtured and measured in a useful way.',
    geoTitle: 'Be found where decisions begin.', geoText: 'Technical SEO, clear information architecture, structured data and semantic content make your offer understandable to people, search engines and AI answer systems – without ranking promises.',
    osEyebrow: 'YOUR BUSINESS OS', osTitle: 'The website is only the front end.',
    osText: 'Behind it, I build exactly the modules your team actually needs. No feature graveyard. No standard software dictating your process.',
    dashboardEyebrow: 'MANAGEMENT COCKPIT · DEMO DATA', dashboardTitle: 'Know what is happening in your business.', dashboardText: 'Do not open ten tools. Get one clear view of what matters now.',
    azEyebrow: 'FROM A TO Z', azTitle: 'One contact. Many possibilities.', azText: 'The range is not a package you have to buy. It is the ability to connect the right parts cleanly.',
    dataEyebrow: 'DATA · SECURITY · AI', dataTitle: 'A dependable architecture beneath the surface.',
    dataText: 'Data is entered once, passed on in a controlled way and made accessible only to the right role. AI supports concrete steps – transparently and with human oversight.',
    securityTitle: 'Security is not an add-on.', securityText: 'Privacy by Design, roles, authentication, data minimisation, secure interfaces, backups and logging are considered from the start. Swiss privacy requirements and GDPR are assessed by project context; blanket compliance guarantees are not made.',
    aiTitle: 'AI that reduces work.', aiText: 'Classify an enquiry, create a CRM record, assign responsibility, prepare a response draft and schedule a follow-up – controlled rather than automated at any cost.',
    casesEyebrow: 'PROOF OVER PROMISES', casesTitle: 'Systems with real substance.', casesText: 'Real projects spanning strategy, brand, UX, frontend, backend, data and processes. Status and limitations are stated transparently.', caseCta: 'View case', live: 'Open live',
    aboutEyebrow: 'MARCEL SPAHR · DIGITAL STUDIO BERN', aboutTitle: 'You do not have to translate between business, design and technology.',
    aboutText: 'I personally guide your project from analysis and UX through architecture and introduction. Business Information Technology, advertising technology and long-standing experience in IT, projects, marketing and sales come together under one responsibility.',
    aboutQuote: 'I listen first, ask questions and then build only what genuinely helps in daily work.',
    facts: [['15+', 'Years in technology and customer projects'], ['HF', 'Business Information Technology, final stage'], ['01', 'Accountable person from analysis to go-live'], ['Bern', 'Based in Switzerland, working beyond it']],
    finalA: 'Your business does not need more tools.', finalB: 'It needs a system.', finalText: 'Let us find the architecture that fits your company, your people and your goals.',
    legal: 'Privacy and legal notice', privacy: 'Privacy', imprint: 'Legal notice', footerLine: 'Digital business systems. Personally developed in Bern.',
  },
} as const;
