export type ExperienceLang = 'de' | 'en';

export const chapters = [
  { id: 'journey-start', short: 'Vision', label: { de: 'Vision', en: 'Vision' } },
  { id: 'fragmentierung', short: 'Heute', label: { de: 'Ausgangslage', en: 'Today' } },
  { id: 'journey-solutions', short: 'System', label: { de: 'Das System', en: 'The system' } },
  { id: 'verkaufssystem', short: 'Web', label: { de: 'Website', en: 'Website' } },
  { id: 'marketing-engine', short: 'Reach', label: { de: 'Marketing', en: 'Marketing' } },
  { id: 'business-os', short: 'Flow', label: { de: 'Prozesse', en: 'Processes' } },
  { id: 'daten-intelligenz', short: 'Data', label: { de: 'Daten & AI', en: 'Data & AI' } },
  { id: 'journey-references', short: 'Proof', label: { de: 'Projekte', en: 'Projects' } },
  { id: 'journey-about', short: 'Marcel', label: { de: 'Zusammenarbeit', en: 'Collaboration' } },
  { id: 'journey-contact', short: 'Start', label: { de: 'Projektstart', en: 'Project start' } },
] as const;

export const systemNodes = {
  de: ['Website', 'Marketing', 'Kunden', 'E-Mail', 'Offerten', 'Projekte', 'Finanzen', 'Mitarbeitende', 'Analytics', 'Daten', 'Termine', 'Social Media'],
  en: ['Website', 'Marketing', 'Customers', 'Email', 'Quotes', 'Projects', 'Finance', 'Team', 'Analytics', 'Data', 'Calendar', 'Social media'],
};

export const flowSteps = {
  de: ['Google-Suche', 'Website', 'Anfrage', 'CRM', 'Termin', 'Beratung', 'Offerte', 'Freigabe', 'Auftrag', 'Projekt'],
  en: ['Google search', 'Website', 'Enquiry', 'CRM', 'Meeting', 'Consultation', 'Quote', 'Approval', 'Order', 'Project'],
};

export const flowStepDetails = {
  de: [
    'Menschen mit einem konkreten Bedarf finden dein Angebot über relevante Suchbegriffe und klar strukturierte Inhalte.',
    'Die Website übersetzt Aufmerksamkeit in Vertrauen und führt Interessierte gezielt zum nächsten sinnvollen Schritt.',
    'Formulare und klare Kontaktwege erfassen die Anfrage vollständig, nachvollziehbar und ohne Medienbruch.',
    'Quelle, Interesse, Kontaktdaten und Verlauf landen in einem zentralen, aktuellen Kundendatensatz.',
    'Qualifizierte Kontakte buchen einen passenden Termin; Bestätigung und Vorbereitung laufen automatisch mit.',
    'Bedarf, Ziele und Rahmenbedingungen werden strukturiert geklärt und direkt im Prozess dokumentiert.',
    'Aus den vorhandenen Informationen entsteht eine verständliche, konsistente und digital versendbare Offerte.',
    'Rückfragen, Anpassungen und Freigabe bleiben transparent; Entscheidungen werden sauber festgehalten.',
    'Die bestätigte Offerte wird ohne doppelte Dateneingabe zum Auftrag mit Verantwortlichkeiten und nächsten Schritten.',
    'Aufgaben, Termine, Kommunikation und Fortschritt bleiben vom Start bis zum Abschluss in einem verbundenen System.',
  ],
  en: [
    'People with a concrete need discover your offer through relevant search terms and clearly structured content.',
    'The website turns attention into trust and guides interested people towards the next useful step.',
    'Forms and clear contact paths capture the enquiry completely, transparently and without manual transfers.',
    'Source, interest, contact details and history are stored in one current customer record.',
    'Qualified contacts book a suitable meeting while confirmation and preparation run automatically.',
    'Needs, goals and constraints are clarified systematically and documented directly in the process.',
    'The available information becomes a clear, consistent quote that can be sent digitally.',
    'Questions, changes and approval remain transparent, with every decision recorded cleanly.',
    'The approved quote becomes an order with responsibilities and next steps, without entering data twice.',
    'Tasks, schedules, communication and progress remain connected from project start to completion.',
  ],
} as const;

export const flowStepInsights = {
  de: [
    { result: 'Passende Besucher mit konkretem Bedarf', automation: 'Quelle und Suchintention bleiben nachvollziehbar', value: 'Weniger Streuverlust in der Akquise' },
    { result: 'Interesse führt zu einem klaren nächsten Schritt', automation: 'Inhalte und Handlungswege greifen ineinander', value: 'Mehr qualifizierte statt anonyme Besuche' },
    { result: 'Eine vollständige, strukturierte Anfrage', automation: 'Formulardaten werden direkt weitergegeben', value: 'Kein Abtippen und keine verlorenen Angaben' },
    { result: 'Ein zentraler, aktueller Kundendatensatz', automation: 'Quelle, Verlauf und Aufgaben bleiben verknüpft', value: 'Eine verlässliche Sicht für Verkauf und Service' },
    { result: 'Ein passender Termin mit qualifiziertem Kontakt', automation: 'Bestätigung und Erinnerung laufen automatisch mit', value: 'Weniger Koordination und weniger Ausfälle' },
    { result: 'Dokumentierter Bedarf und klare Ziele', automation: 'Notizen und nächste Schritte bleiben am Kontakt', value: 'Bessere Entscheidungen ohne Wissensverlust' },
    { result: 'Eine konsistente und verständliche Offerte', automation: 'Kundendaten und Leistungen werden übernommen', value: 'Schneller versenden und Fehler vermeiden' },
    { result: 'Eine nachvollziehbare Entscheidung', automation: 'Status, Rückfragen und Versionen bleiben sichtbar', value: 'Kürzere Abstimmung und klare Verbindlichkeit' },
    { result: 'Ein sauber vorbereiteter Projektstart', automation: 'Die Freigabe wird in Aufgaben und Rollen überführt', value: 'Keine doppelte Datenerfassung' },
    { result: 'Transparente Umsetzung bis zum Abschluss', automation: 'Termine, Aufgaben und Kommunikation bleiben verbunden', value: 'Mehr Übersicht für Team und Kundschaft' },
  ],
  en: [
    { result: 'Relevant visitors with a concrete need', automation: 'Source and search intent remain traceable', value: 'Less wasted effort in acquisition' },
    { result: 'Interest leads to one clear next step', automation: 'Content and calls to action work together', value: 'More qualified rather than anonymous visits' },
    { result: 'A complete and structured enquiry', automation: 'Form data is passed on directly', value: 'No retyping and no missing information' },
    { result: 'One central and current customer record', automation: 'Source, history and tasks remain connected', value: 'A reliable view for sales and service' },
    { result: 'A suitable meeting with a qualified contact', automation: 'Confirmation and reminders run automatically', value: 'Less coordination and fewer no-shows' },
    { result: 'Documented needs and clear objectives', automation: 'Notes and next steps remain with the contact', value: 'Better decisions without knowledge loss' },
    { result: 'A consistent and understandable quote', automation: 'Customer data and services are carried over', value: 'Send faster and avoid errors' },
    { result: 'A traceable decision', automation: 'Status, questions and versions remain visible', value: 'Faster alignment and clear commitment' },
    { result: 'A properly prepared project start', automation: 'Approval becomes tasks and responsibilities', value: 'No duplicate data entry' },
    { result: 'Transparent delivery through completion', automation: 'Dates, tasks and communication stay connected', value: 'Greater clarity for the team and client' },
  ],
} as const;

export const copy = {
  de: {
    skip: 'Zum Inhalt springen', menu: 'Kapitel', close: 'Schliessen', project: 'Projekt besprechen', discover: 'System entdecken',
    heroEyebrow: 'DIGITALE UNTERNEHMENSSYSTEME · BERN, SCHWEIZ',
    heroTitleA: 'Dein digitales Unternehmen.', heroTitleB: 'Aus einem Guss.',
    heroText: 'Ich verbinde Website, Marketing, Daten, CRM, ERP, AI und Automationen zu einem System, das Kunden gewinnt und Arbeit reduziert.',
    heroNote: 'Individuell entwickelt. Persönlich verantwortet.',
    problemEyebrow: 'DIE AUSGANGSLAGE', problemTitle: 'Das Problem sind nicht zu wenige Tools.', problemTitleGold: 'Sondern zu viele Übergaben.',
    problemText: 'Daten werden kopiert. Anfragen gehen verloren. Mitarbeitende suchen Informationen. Jede Insellösung erzeugt neue Arbeit zwischen den Systemen.',
    problemQuote: 'Software hilft erst dann, wenn sie zusammenspielt.',
    systemEyebrow: 'DIE TRANSFORMATION', systemTitle: 'Aus Einzellösungen wird ein System.',
    systemText: 'Ich analysiere zuerst Abläufe, Ziele und bestehende Werkzeuge. Danach entsteht eine Architektur, in der jeder Baustein eine klare Aufgabe erfüllt.',
    systemCore: 'DEIN SYSTEM', systemPrinciple: 'Nicht mehr Software. Die richtige Software.', systemCta: 'Was wäre für mein Unternehmen sinnvoll?',
    webEyebrow: 'WEBSITE ALS VERKAUFSSYSTEM', webTitle: 'Deine Website hört nicht beim Design auf.', webTitleGold: 'Sie beginnt dort erst zu arbeiten.',
    webText: 'Jeder Kontakt kann strukturiert weitergeführt werden – von der ersten Suche bis zum Auftrag und darüber hinaus.',
    marketingEyebrow: 'MARKETING & VERKAUF', marketingTitle: 'Aus Sichtbarkeit werden echte Anfragen.',
    marketingText: 'Egal ob jemand über Google, Social Media oder eine Empfehlung kommt: Jede Anfrage landet am richtigen Ort, erhält einen nächsten Schritt und bleibt bis zum Abschluss nachvollziehbar.',
    geoTitle: 'Gefunden werden, wo Entscheidungen beginnen.', geoText: 'Technische SEO, klare Informationsarchitektur, strukturierte Daten und semantische Inhalte machen dein Angebot für Menschen, Suchmaschinen und AI-Antwortsysteme verständlich – ohne Ranking-Versprechen.',
    osEyebrow: 'DEIN BUSINESS OS', osTitle: 'Die Website ist nur die Vorderseite.',
    osText: 'Dahinter können genau die Module entstehen, die dein Team wirklich braucht. Kein Funktionsfriedhof. Keine Standardsoftware, die den Prozess diktiert.',
    dashboardEyebrow: 'MANAGEMENT COCKPIT · DEMODATEN', dashboardTitle: 'Wissen, was im Unternehmen passiert.', dashboardText: 'Nicht zehn Tools öffnen. Eine klare Sicht auf die Informationen, die jetzt relevant sind.',
    dataEyebrow: 'DATEN · SECURITY · AI', dataTitle: 'Eine verlässliche Architektur unter der Oberfläche.',
    dataText: 'Daten werden einmal erfasst, kontrolliert weitergegeben und nur für die jeweilige Rolle zugänglich gemacht. AI unterstützt konkrete Schritte – nachvollziehbar und mit menschlicher Kontrolle.',
    securityTitle: 'Sicherheit ist kein Zusatz.', securityText: 'Privacy by Design, Rollen, Authentifizierung, Datenminimierung, sichere Schnittstellen, Backups und Logging werden von Beginn an berücksichtigt. Schweizer Datenschutzanforderungen und die DSGVO werden je nach Projektkontext geprüft; pauschale Compliance-Garantien gibt es nicht.',
    aiTitle: 'AI, die Arbeit abnimmt.', aiText: 'Eine Anfrage klassifizieren, einen CRM-Datensatz anlegen, die Zuständigkeit bestimmen, einen Antwortentwurf vorbereiten und ein Follow-up planen – kontrolliert statt automatisch um jeden Preis.',
    casesEyebrow: 'BEWEIS STATT BEHAUPTUNG', casesTitle: 'Systeme, die bereits Substanz haben.', casesText: 'Echte Projekte aus Strategie, Marke, UX, Frontend, Backend, Daten und Prozessen. Status und Grenzen sind transparent ausgewiesen.', caseCta: 'Case ansehen', live: 'Live öffnen',
    aboutEyebrow: 'MENSCHLICHE URTEILSKRAFT × KI', aboutTitle: 'Erfahrung entscheidet. KI verstärkt.',
    aboutText: 'Ich verbinde über 15 Jahre Erfahrung in Technologie und Kundenprojekten mit präzisen KI-Werkzeugen. So entstehen schneller klare Analysen, fundierte Entscheidungen und Lösungen, die im Unternehmen wirklich tragen.',
    aboutQuote: 'KI liefert Tempo und Perspektiven. Ich liefere Kontext, Urteilskraft und übernehme die Verantwortung.',
    facts: [['15+', 'Jahre Praxis in Technologie und Kundenprojekten'], ['HF', 'Wirtschaftsinformatik in der Abschlussphase'], ['MENSCH + KI', 'Urteilskraft und Geschwindigkeit verbunden'], ['01', 'Verantwortung von der Analyse bis zum Betrieb']],
    finalA: 'Dein Unternehmen braucht nicht mehr Tools.', finalB: 'Es braucht ein System.', finalText: 'Lass uns herausfinden, welche Architektur zu deinem Unternehmen, deinen Menschen und deinen Zielen passt.',
    legal: 'Datenschutz und Impressum', privacy: 'Datenschutz', imprint: 'Impressum', footerLine: 'Digitale Unternehmenssysteme. Persönlich entwickelt in Bern.',
  },
  en: {
    skip: 'Skip to content', menu: 'Chapters', close: 'Close', project: 'Discuss your project', discover: 'Discover the system',
    heroEyebrow: 'DIGITAL BUSINESS SYSTEMS · BERN, SWITZERLAND',
    heroTitleA: 'Your digital business.', heroTitleB: 'Built as one system.',
    heroText: 'I connect websites, marketing, data, CRM, ERP, AI and automation into one system that wins customers and reduces work.',
    heroNote: 'Custom-built. Personally accountable.',
    problemEyebrow: 'THE CURRENT REALITY', problemTitle: 'The problem is not a lack of tools.', problemTitleGold: 'It is the gaps between them.',
    problemText: 'Data is copied. Enquiries get lost. Teams search for information. Every isolated solution creates more work between systems.',
    problemQuote: 'Software only helps when it works together.',
    systemEyebrow: 'THE TRANSFORMATION', systemTitle: 'Separate solutions become one system.',
    systemText: 'I first analyse workflows, goals and existing tools. Then I create an architecture in which every component has a clear purpose.',
    systemCore: 'YOUR SYSTEM', systemPrinciple: 'Not more software. The right software.', systemCta: 'What would make sense for my company?',
    webEyebrow: 'WEBSITE AS A SALES SYSTEM', webTitle: 'Your website does not stop at design.', webTitleGold: 'That is where it starts working.',
    webText: 'Every contact can move forward in a structured way – from the first search to the order and beyond.',
    marketingEyebrow: 'MARKETING & SALES', marketingTitle: 'Visibility becomes real enquiries.',
    marketingText: 'Whether someone arrives through Google, social media or a referral, every enquiry reaches the right place, receives a clear next step and remains traceable through to the outcome.',
    geoTitle: 'Be found where decisions begin.', geoText: 'Technical SEO, clear information architecture, structured data and semantic content make your offer understandable to people, search engines and AI answer systems – without ranking promises.',
    osEyebrow: 'YOUR BUSINESS OS', osTitle: 'The website is only the front end.',
    osText: 'Behind it, I build exactly the modules your team actually needs. No feature graveyard. No standard software dictating your process.',
    dashboardEyebrow: 'MANAGEMENT COCKPIT · DEMO DATA', dashboardTitle: 'Know what is happening in your business.', dashboardText: 'Do not open ten tools. Get one clear view of what matters now.',
    dataEyebrow: 'DATA · SECURITY · AI', dataTitle: 'A dependable architecture beneath the surface.',
    dataText: 'Data is entered once, passed on in a controlled way and made accessible only to the right role. AI supports concrete steps – transparently and with human oversight.',
    securityTitle: 'Security is not an add-on.', securityText: 'Privacy by Design, roles, authentication, data minimisation, secure interfaces, backups and logging are considered from the start. Swiss privacy requirements and GDPR are assessed by project context; blanket compliance guarantees are not made.',
    aiTitle: 'AI that reduces work.', aiText: 'Classify an enquiry, create a CRM record, assign responsibility, prepare a response draft and schedule a follow-up – controlled rather than automated at any cost.',
    casesEyebrow: 'PROOF OVER PROMISES', casesTitle: 'Systems with real substance.', casesText: 'Real projects spanning strategy, brand, UX, frontend, backend, data and processes. Status and limitations are stated transparently.', caseCta: 'View case', live: 'Open live',
    aboutEyebrow: 'HUMAN JUDGEMENT × AI', aboutTitle: 'Experience decides. AI amplifies.',
    aboutText: 'I combine more than 15 years of technology and client-project experience with precise AI tools. The result is faster analysis, better-founded decisions and solutions built to work in the real organisation.',
    aboutQuote: 'AI brings speed and new perspectives. I bring context, judgement and personal accountability.',
    facts: [['15+', 'Years in technology and customer projects'], ['HF', 'Business Information Technology, final stage'], ['HUMAN + AI', 'Judgement and speed working together'], ['01', 'Accountability from analysis through operation']],
    finalA: 'Your business does not need more tools.', finalB: 'It needs a system.', finalText: 'Let us find the architecture that fits your company, your people and your goals.',
    legal: 'Privacy and legal notice', privacy: 'Privacy', imprint: 'Legal notice', footerLine: 'Digital business systems. Personally developed in Bern.',
  },
} as const;
